"""Trading event publisher for AI-driven high-frequency trading guidance.

This module implements the trading event publisher that takes AI analysis results,
validates them, and publishes trading guidance events to external Redis channels
for consumption by high-frequency trading executors.
"""

import json
import logging
import asyncio
from typing import Any, Optional
from datetime import datetime, timezone

import redis.asyncio as redis
from pydantic import BaseModel, Field, field_validator

from ..utils.config import TradingEventPublisherConfig

logger = logging.getLogger(__name__)


class TradingEvent(BaseModel):
    """Trading event structure for AI-generated trading guidance."""

    grid_delta: float = Field(..., description="Price delta for grid trading")
    grid_quantity: float = Field(..., description="Order quantity for grid trading")
    active_side: str = Field(..., description="Trading side: Buy or Sell")

    @field_validator('grid_delta')
    @classmethod
    def validate_grid_delta(cls, v):
        if v <= 0:
            raise ValueError("grid_delta must be positive")
        return v

    @field_validator('grid_quantity')
    @classmethod
    def validate_grid_quantity(cls, v):
        if v <= 0:
            raise ValueError("grid_quantity must be positive")
        return v

    @field_validator('active_side')
    @classmethod
    def validate_active_side(cls, v):
        if v not in ["Buy", "Sell"]:
            raise ValueError("active_side must be 'Buy' or 'Sell'")
        return v


class EventValidationError(Exception):
    """Exception raised when trading event validation fails."""
    pass


class RedisPublishError(Exception):
    """Exception raised when Redis publishing fails."""
    pass


class TradingEventPublisher:
    """Publisher for AI-generated trading events to external Redis channels.

    This component validates trading events generated by AI analysis and
    publishes them to a Redis channel for consumption by external trading
    executors. It includes comprehensive validation, retry logic, and
    error handling.
    """

    def __init__(self, config: TradingEventPublisherConfig):
        """Initialize the trading event publisher.

        Args:
            config: Trading event publisher configuration
        """
        self.config = config
        self.redis_client: Optional[redis.Redis] = None
        self._is_connected = False

        logger.info(
            f"TradingEventPublisher initialized - "
            f"Redis: {config.redis.host}:{config.redis.port}, "
            f"Channel: {config.redis.channel}, "
            f"Enabled: {config.enable}"
        )

    async def _create_redis_connection(self) -> redis.Redis:
        """Create Redis connection with connection pooling and configured parameters.

        Returns:
            Configured Redis client

        Raises:
            RedisConnectionError: If connection fails
        """
        try:
            # Create connection pool
            pool = redis.ConnectionPool.from_url(
                f"redis://{self.config.redis.host}:{self.config.redis.port}/{self.config.redis.db}",
                password=self.config.redis.password,
                socket_timeout=self.config.redis.timeout,
                socket_connect_timeout=self.config.redis.timeout,
                decode_responses=True,
                max_connections=self.config.redis.max_connections,
                retry_on_timeout=self.config.redis.retry_on_timeout,
                socket_keepalive=self.config.redis.socket_keepalive,
                socket_keepalive_options=self.config.redis.socket_keepalive_options,
                health_check_interval=self.config.redis.health_check_interval
            )

            self.redis_client = redis.Redis(connection_pool=pool)

            # Test connection
            ping_result = await self.redis_client.ping()
            if not isinstance(ping_result, bool):
                raise RedisConnectionError("Unexpected ping response type")

            self._is_connected = True
            logger.info(
                f"Redis connection established with pooling: {self.config.redis.host}:{self.config.redis.port} "
                f"(max_connections: {self.config.redis.max_connections})"
            )

            return self.redis_client

        except Exception as e:
            self._is_connected = False
            logger.error(f"Failed to connect to Redis: {e}")
            raise RedisConnectionError(f"Redis connection failed: {e}") from e

    async def _close_redis_connection(self) -> None:
        """Close Redis connection."""
        if self.redis_client:
            try:
                await self.redis_client.close()
                self._is_connected = False
                logger.info("Redis connection closed")
            except Exception as e:
                logger.error(f"Error closing Redis connection: {e}")

    def _validate_event_values(self, event_data: dict[str, Any]) -> None:
        """Validate trading event values against configured constraints.

        Args:
            event_data: Raw event data from AI analysis

        Raises:
            EventValidationError: If validation fails
        """
        validation_config = self.config.validation

        # Extract numeric values
        grid_delta = event_data.get("grid_delta")
        grid_quantity = event_data.get("grid_quantity")
        active_side = event_data.get("active_side")

        # Validate grid_delta
        if grid_delta is None:
            raise EventValidationError("grid_delta is required")
        if not isinstance(grid_delta, (int, float)):
            raise EventValidationError("grid_delta must be a number")
        if grid_delta < validation_config.min_grid_delta:
            raise EventValidationError(
                f"grid_delta {grid_delta} is below minimum {validation_config.min_grid_delta}"
            )
        if grid_delta > validation_config.max_grid_delta:
            raise EventValidationError(
                f"grid_delta {grid_delta} is above maximum {validation_config.max_grid_delta}"
            )

        # Validate grid_quantity
        if grid_quantity is None:
            raise EventValidationError("grid_quantity is required")
        if not isinstance(grid_quantity, (int, float)):
            raise EventValidationError("grid_quantity must be a number")
        if grid_quantity < validation_config.min_grid_quantity:
            raise EventValidationError(
                f"grid_quantity {grid_quantity} is below minimum {validation_config.min_grid_quantity}"
            )
        if grid_quantity > validation_config.max_grid_quantity:
            raise EventValidationError(
                f"grid_quantity {grid_quantity} is above maximum {validation_config.max_grid_quantity}"
            )

        # Validate active_side
        if active_side is None:
            raise EventValidationError("active_side is required")
        if active_side not in ["Buy", "Sell"]:
            raise EventValidationError(
                f"active_side '{active_side}' must be 'Buy' or 'Sell'"
            )

    def _extract_trading_event_from_ai_response(self, ai_response: str) -> Optional[dict[str, Any]]:
        """Extract trading event JSON from AI analysis response.

        Args:
            ai_response: Raw AI analysis response text

        Returns:
            Extracted trading event data or None if not found

        Raises:
            EventValidationError: If JSON extraction or parsing fails
        """
        try:
            import re

            # Strategy 1: Look for JSON code block with proper formatting
            json_patterns = [
                # Pattern 1: ```json block with newlines
                r'```(?:json)?\s*\n(.*?)\n```',
                # Pattern 2: Inline code block
                r'`([^`]*"grid_delta"[^`]*)`',
                # Pattern 3: JSON object with grid_delta field (more flexible)
                r'\{[^{}]*"grid_delta"\s*:\s*[^,}]*[^{}]*\}',
                # Pattern 4: Single quotes JSON (common in some AI outputs)
                r"'[^']*'grid_delta'[^']*'",
            ]

            json_str = None
            pattern_used = None

            for i, pattern in enumerate(json_patterns):
                try:
                    if i == 0:  # Code block pattern
                        json_matches = re.findall(pattern, ai_response, re.DOTALL)
                        if json_matches:
                            json_str = json_matches[0].strip()
                            pattern_used = f"code_block_{i+1}"
                            break
                    else:
                        json_matches = re.findall(pattern, ai_response, re.DOTALL)
                        if json_matches:
                            # Clean up the JSON string
                            candidate = json_matches[0].strip()

                            # Try to clean common formatting issues
                            candidate = re.sub(r',\s*}', '}', candidate)  # Remove trailing commas
                            candidate = re.sub(r',\s*]', ']', candidate)  # Remove trailing commas in arrays
                            candidate = candidate.strip("'\"")  # Remove surrounding quotes if present

                            # Basic validation before parsing
                            if candidate.startswith('{') and candidate.endswith('}'):
                                json_str = candidate
                                pattern_used = f"pattern_{i+1}"
                                break
                except Exception as e:
                    logger.debug(f"Pattern {i+1} failed: {e}")
                    continue

            if not json_str:
                logger.warning("No trading event JSON found in AI response")
                return None

            logger.debug(f"Found JSON using pattern: {pattern_used}")
            logger.debug(f"Raw JSON string: {json_str[:200]}...")

            # Strategy 2: Enhanced JSON parsing with error recovery
            try:
                event_data = json.loads(json_str)
            except json.JSONDecodeError as e:
                # Try to fix common JSON issues
                try:
                    # Fix unescaped quotes in strings
                    fixed_json = re.sub(r'(?<!\\)"(?=[^,:}\s]*":)', r'\\"', json_str)
                    event_data = json.loads(fixed_json)
                    logger.info("Fixed JSON parsing issues successfully")
                except json.JSONDecodeError:
                    # Try a more aggressive cleanup
                    try:
                        # Extract just the trading event fields if the whole JSON is malformed
                        field_patterns = {
                            'grid_delta': r'"grid_delta"\s*:\s*([0-9.]+)',
                            'grid_quantity': r'"grid_quantity"\s*:\s*([0-9.]+)',
                            'active_side': r'"active_side"\s*:\s*"([^"]+)"'
                        }

                        extracted_data = {}
                        for field, pattern in field_patterns.items():
                            match = re.search(pattern, ai_response)
                            if match:
                                value = match.group(1)
                                if field in ['grid_delta', 'grid_quantity']:
                                    extracted_data[field] = float(value)
                                else:
                                    extracted_data[field] = value

                        if len(extracted_data) == 3:
                            event_data = extracted_data
                            logger.info("Extracted trading event fields using regex fallback")
                        else:
                            raise EventValidationError(f"Could not extract all required fields. Found: {list(extracted_data.keys())}")
                    except Exception:
                        raise EventValidationError(f"Failed to parse trading event JSON: {e}")

            # Strategy 3: Validate extracted data
            if not isinstance(event_data, dict):
                raise EventValidationError("Extracted data is not a dictionary")

            required_fields = ["grid_delta", "grid_quantity", "active_side"]
            missing_fields = [field for field in required_fields if field not in event_data]

            if missing_fields:
                raise EventValidationError(
                    f"Missing required fields in trading event: {missing_fields}"
                )

            # Strategy 4: Validate field types and values
            try:
                # Convert numeric fields to proper types
                if not isinstance(event_data["grid_delta"], (int, float)):
                    event_data["grid_delta"] = float(event_data["grid_delta"])
                if not isinstance(event_data["grid_quantity"], (int, float)):
                    event_data["grid_quantity"] = float(event_data["grid_quantity"])

                # Validate active_side
                if not isinstance(event_data["active_side"], str):
                    event_data["active_side"] = str(event_data["active_side"])
                event_data["active_side"] = event_data["active_side"].strip().title()

                if event_data["active_side"] not in ["Buy", "Sell"]:
                    raise EventValidationError(
                        f"Invalid active_side value: {event_data['active_side']}"
                    )

            except (ValueError, TypeError) as e:
                raise EventValidationError(f"Invalid field types in trading event: {e}")

            logger.info(f"Successfully extracted trading event: {event_data}")
            return event_data

        except EventValidationError:
            raise
        except Exception as e:
            raise EventValidationError(f"Unexpected error extracting trading event: {e}")

    async def _publish_event(self, event_data: dict[str, Any]) -> None:
        """Publish validated trading event to Redis channel.

        Args:
            event_data: Validated trading event data

        Raises:
            RedisPublishError: If publishing fails
        """
        if not self._is_connected or not self.redis_client:
            await self._create_redis_connection()

        try:
            # Create structured event message with metadata
            event_message = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "source": "strategy_agent_unified_analysis",
                "event_type": "trading_guidance",
                "data": event_data
            }

            # Publish to Redis channel
            published = await self.redis_client.publish(
                self.config.redis.channel,
                json.dumps(event_message)
            )

            if published > 0:
                logger.info(
                    f"Trading event published to channel '{self.config.redis.channel}' "
                    f"(reached {published} subscribers): {event_data}"
                )
            else:
                logger.warning(
                    f"Trading event published but no subscribers on channel '{self.config.redis.channel}'"
                )

        except Exception as e:
            raise RedisPublishError(f"Failed to publish trading event: {e}") from e

    async def _publish_with_retry(self, event_data: dict[str, Any]) -> bool:
        """Publish trading event with retry logic.

        Args:
            event_data: Validated trading event data

        Returns:
            True if publishing succeeded, False otherwise
        """
        max_retries = self.config.redis.max_retries
        base_delay = 1.0

        for attempt in range(max_retries + 1):
            try:
                await self._publish_event(event_data)
                return True

            except (RedisConnectionError, RedisPublishError) as e:
                if attempt == max_retries:
                    logger.error(f"Failed to publish trading event after {max_retries + 1} attempts: {e}")
                    return False

                delay = base_delay * (2 ** attempt)  # Exponential backoff
                logger.warning(
                    f"Publish attempt {attempt + 1} failed, retrying in {delay}s: {e}"
                )
                await asyncio.sleep(delay)

                # Try to reconnect
                if not self._is_connected:
                    try:
                        await self._create_redis_connection()
                    except Exception:
                        pass  # Will retry in next attempt

        return False

    async def process_ai_analysis_and_publish(self, ai_analysis_response: str) -> bool:
        """Process AI analysis response and publish trading event if available.

        This is the main entry point that extracts trading events from AI analysis,
        validates them, and publishes them to the Redis channel.

        Args:
            ai_analysis_response: Raw AI analysis response text

        Returns:
            True if event was successfully published, False otherwise

        Raises:
            Various exceptions for critical failures
        """
        if not self.config.enable:
            logger.debug("Trading event publisher is disabled")
            return False

        try:
            # Extract trading event from AI response
            event_data = self._extract_trading_event_from_ai_response(ai_analysis_response)

            if event_data is None:
                logger.info("No trading event found in AI analysis response")
                return False

            # Validate event values
            self._validate_event_values(event_data)

            # Create structured trading event
            trading_event = TradingEvent(**event_data)
            validated_event_data = trading_event.model_dump()

            # Publish with retry
            success = await self._publish_with_retry(validated_event_data)

            if success:
                logger.info("Trading event published successfully")
            else:
                logger.error("Failed to publish trading event after retries")

            return success

        except EventValidationError as e:
            logger.error(f"Trading event validation failed: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error processing trading event: {e}")
            return False

    async def test_connection(self) -> bool:
        """Test Redis connection and configuration.

        Returns:
            True if connection test succeeds, False otherwise
        """
        if not self.config.enable:
            logger.debug("Trading event publisher is disabled")
            return True

        try:
            await self._create_redis_connection()

            # Test publish a test message
            test_message = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "source": "strategy_agent_test",
                "event_type": "connection_test",
                "data": {"test": True}
            }

            published = await self.redis_client.publish(
                self.config.redis.channel,
                json.dumps(test_message)
            )

            logger.info(f"Connection test successful (reached {published} subscribers)")
            return True

        except Exception as e:
            logger.error(f"Connection test failed: {e}")
            return False
        finally:
            await self._close_redis_connection()

    async def close(self) -> None:
        """Close the trading event publisher and clean up resources."""
        logger.info("Closing TradingEventPublisher")

        await self._close_redis_connection()

        logger.info("TradingEventPublisher closed")

    def get_status(self) -> dict[str, Any]:
        """Get current publisher status.

        Returns:
            Status dictionary with connection and configuration info
        """
        return {
            "enabled": self.config.enable,
            "connected": self._is_connected,
            "redis_config": {
                "host": self.config.redis.host,
                "port": self.config.redis.port,
                "channel": self.config.redis.channel,
                "db": self.config.redis.db
            },
            "validation_config": {
                "grid_delta_range": (
                    self.config.validation.min_grid_delta,
                    self.config.validation.max_grid_delta
                ),
                "grid_quantity_range": (
                    self.config.validation.min_grid_quantity,
                    self.config.validation.max_grid_quantity
                )
            }
        }


class RedisConnectionError(Exception):
    """Exception raised when Redis connection fails."""
    pass